# **Import**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import plotly.graph_objs as go
import plotly.express as px
from plotly.subplots import make_subplots
plt.style.use('dark_background')

# **Penguins**

In [3]:
penguins = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv")
penguins.head(1)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE

In [4]:
df_penguins = sns.load_dataset('penguins')
df_penguins.head(1)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male

**Описание данных `df_penguins`**:

- **`species:`** вид пингвина (например, Adelie, Chinstrap, Gentoo)
- **`island:`** остров, на котором был найден пингвин (например, Torgersen, Dream, Biscoe)
- **`bill_length_mm:`** длина клюва в миллиметрах
- **`bill_depth_mm:`** глубина клюва в миллиметрах
- **`flipper_length_mm:`** длина плавника в миллиметрах
- **`body_mass_g:`** масса тела в граммах
- **`sex:`** пол пингвина (мужской, женский или неизвестный)

# **Diamonds**

In [5]:
df_diamonds = sns.load_dataset('diamonds')
df_diamonds.head(1)

   carat    cut color clarity  depth  table  price     x     y     z
0   0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43

**Описание данных `df_diamonds`**:

- **`carat:`** вес бриллианта в каратах (1 карат = 0.2 грамма)
- **`cut:`** качество огранки (Fair, Good, Very Good, Premium, Ideal)
- **`color:`** цвет (D — бесцветный, далее E, F, G и т.д. по убыванию ценности)
- **`clarity:`** чистота (I1, SI2, SI1, VS2, VS1, VVS2, VVS1, IF)
- **`depth:`** глубина (процентное соотношение глубины к диаметру)
- **`table:`** ширина верхней грани (процент от общей ширины)
- **`price:`** цена в долларах США
- **`x:`** длина в миллиметрах
- **`y:`** ширина в миллиметрах
- **`z:`** глубина в миллиметрах

# **MPG**

In [6]:
df_mpg = sns.load_dataset('mpg')
df_mpg.head(1)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu

**Описание данных `df_mpg`**:

- **`mpg:`** расход топлива (мили на галлон)
- **`cylinders:`** количество цилиндров.  
- **`displacement:`** объем двигателя (кубические дюймы)
- **`horsepower:`** мощность (лошадиные силы)
- **`weight:`** вес автомобиля (фунты).  
- **`acceleration:`** время разгона 0–60 миль/ч (секунды)
- **`model_year:`** год выпуска модели.  
- **`origin:`** страна-производитель (США, Европа, Япония)
- **`name:`** название модели

# **Tips**

In [7]:
df_tips = px.data.tips()
df_tips.head(1)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2

**Описание данных `df_tips`**:

- **`total_bill:`** сумма счета
- **`tip:`** сумма чаевых
- **`sex:`** пол посетителя
- **`smoker:`** курящий/некурящий  
- **`day:`** день недели
- **`time:`** время посещения (обед/ужин)
- **`size:`** количество человек за столом

# **Iris**

In [8]:
df_iris = px.data.iris()
df_iris.head(1)

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1

**Описание данных `df_iris`**:

- **`sepal_length:`** длина чашелистика (см)
- **`sepal_width:`** ширина чашелистика (см)
- **`petal_length:`** длина лепестка (см)
- **`petal_width:`** ширина лепестка (см)
- **`species:`** вид ириса (setosa, versicolor, virginica)
- **`species_id:`** id вида ириса

# **Exercise**

In [9]:
df_exercise = sns.load_dataset('exercise')
df_exercise.head(1)

   Unnamed: 0  id     diet  pulse   time  kind
0           0   1  low fat     85  1 min  rest

**Описание данных `df_exercise`**:

- **`id:`** идентификатор участника
- **`diet:`** тип диеты (no fat, low fat)
- **`pulse:`** средний пульс после упражнения
- **`time:`** время выполнения упражнения (минуты)
- **`kind:`** тип упражнения (running, walking, rest)

# **Taxis**

In [10]:
df_taxis = sns.load_dataset('taxis')
df_taxis.head(1)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.6,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan

**Описание данных `df_taxis`**:

- **`pickup:`** дата и время посадки
- **`dropoff:`** дата и время высадки
- **`passengers:`** количество пассажиров
- **`distance:`** расстояние (мили)
- **`fare:`** стоимость поездки (доллары)
- **`tip:`** чаевые (доллары)
- **`tolls:`** плата за дороги (доллары)
- **`total:`** общая стоимость (доллары)
- **`color:`** цвет такси (желтый/зеленый)
- **`payment:`** способ оплаты (наличные/карта)
- **`pickup_zone:`** зона посадки
- **`dropoff_zone:`** зона высадки
- **`pickup_borough:`** район посадки (Manhattan, Queens и др.)
- **`dropoff_borough:`** район высадки

# **Gapminder**

In [11]:
df_gapminder = px.data.gapminder()
df_gapminder.head(1)

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4

**Описание данных `df_gapminder`**:

- **`country:`** название страны
- **`continent:`** континент
- **`year:`** год
- **`lifeExp:`** ожидаемая продолжительность жизни
- **`pop:`** численность населения
- **`gdpPercap:`** ВВП на душу населения

# **Medals Long**

In [12]:
df_medals_long = px.data.medals_long()
df_medals_long.head(1)

        nation medal  count
0  South Korea  gold     24

**Описание данных `df_medals_long`**:

- **`nation:`** страна
- **`medal:`** тип медали (gold, silver, bronze)
- **`count:`** количество медалей

# **Stocks**

In [13]:
df_stocks = px.data.stocks()
df_stocks.head(1)

         date  GOOG  AAPL  AMZN   FB  NFLX  MSFT
0  2018-01-01   1.0   1.0   1.0  1.0   1.0   1.0

**Описание данных `df_stocks`**:

- **`date:`** дата
- **`GOOG:`** цена акций Google
- **`AAPL:`** цена акций Apple
- **`AMZN:`** цена акций Amazon
- **`FB:`** цена акций Facebook
- **`NFLX:`** цена акций Netflix
- **`MSFT:`** цена акций Microsoft

# **Data USA States**

In [14]:
data_usa_states = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/2014_usa_states.csv")
data_usa_states.head(1)

   Rank    State Postal  Population
0     1  Alabama     AL   4849377.0

**Описание данных `data_usa_states`**:

- **`Rank:`** ранг штата по населению
- **`State:`** название штата
- **`Population:`** численность населения

# **US Cities Top 1k**

In [15]:
us_cities_us_cities_top_1k = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/us-cities-top-1k.csv")
us_cities_us_cities_top_1k.head(1)

         City       State  Population        lat         lon
0  Marysville  Washington       63269  48.051764 -122.177082

**Описание данных `us_cities_top_1k`**:

- **`City:`** название города
- **`State:`** штат
- **`Population:`** население
- **`lat:`** широта
- **`lon:`** долгота

# **Election**

In [16]:
df_election = px.data.election()
df_election.head(1)

,district,Coderre,Bergeron,Joly,total,winner,result,district_id
0,101-Bois-de-Liesse,2481,1829,3024,7334,Joly,plurality,101

**Описание данных `df_election`**:

- **`district:`** избирательный округ
- **`winner:`** победитель
- **`total:`** общее количество голосов
- **`Coderre:`** голоса за Coderre
- **`Bergeron:`** голоса за Bergeron
- **`Joly:`** голоса за Joly

# **DF Fips_Unemp_16**

In [17]:
df_fips_unemp_16 = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv",
                   dtype={"fips": str})
df_fips_unemp_16.head(1)

    fips  unemp
0  01001    5.3

**Описание данных `df_fips_unemp_16`**:

- **`fips:`** код FIPS (идентификатор региона)
- **`unemp:`** уровень безработицы

# **DF Office Sales**

In [18]:
df_office_sales = pd.read_csv('https://raw.githubusercontent.com/ashok-python/data/master/dm_office_sales.csv')
df_office_sales.head(1)

,division,level of education,training level,work experience,salary,sales
0,printers,some college,2,6,91684,372302

**Описание данных `df_office_sales`**:

- **`division:`** регион продаж
- **`level_of_education:`** уровень образования сотрудника
- **`training_level:`** уровень обучения
- **`years_of_experience:`** опыт работы (годы)
- **`salary:`** зарплата
- **`sales:`** объем продаж